name: check

on:
  pull_request:
    branches:
      - master
      - release-*

jobs:

  check:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.4
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: go/src/github.com/${{ github.repository }}

      - name: check
        run: |
          # workaround for https://github.com/actions/setup-go/issues/14
          mkdir -p tools/bin
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b .tools/bin v1.21.0
          export GOPATH=${GITHUB_WORKSPACE}/go
          export PATH=$PATH:$GOPATH/bin
          make check
          make test_part_1
        working-directory: ${{ github.workspace }}/go/src/github.com/${{ github.repository }}
